[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#556B2F"
backgroundColor = "#EFF5D2"
secondaryBackgroundColor = "#C6D870"
textColor = "#445625"
font = "sans serif"

[browser]
gatherUsageStats = false